// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: cron_server_worker.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on WorkerGroup with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *WorkerGroup) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WorkerGroup with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in WorkerGroupMultiError, or
// nil if none found.
func (m *WorkerGroup) ValidateAll() error {
	return m.validate(true)
}

func (m *WorkerGroup) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return WorkerGroupMultiError(errors)
	}

	return nil
}

// WorkerGroupMultiError is an error wrapping multiple validation errors
// returned by WorkerGroup.ValidateAll() if the designated constraints aren't met.
type WorkerGroupMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WorkerGroupMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WorkerGroupMultiError) AllErrors() []error { return m }

// WorkerGroupValidationError is the validation error returned by
// WorkerGroup.Validate if the designated constraints aren't met.
type WorkerGroupValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WorkerGroupValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WorkerGroupValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WorkerGroupValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WorkerGroupValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WorkerGroupValidationError) ErrorName() string { return "WorkerGroupValidationError" }

// Error satisfies the builtin error interface
func (e WorkerGroupValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWorkerGroup.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WorkerGroupValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WorkerGroupValidationError{}

// Validate checks the field values on AllWorkerGroupReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AllWorkerGroupReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AllWorkerGroupReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AllWorkerGroupReplyMultiError, or nil if none found.
func (m *AllWorkerGroupReply) ValidateAll() error {
	return m.validate(true)
}

func (m *AllWorkerGroupReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AllWorkerGroupReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AllWorkerGroupReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AllWorkerGroupReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return AllWorkerGroupReplyMultiError(errors)
	}

	return nil
}

// AllWorkerGroupReplyMultiError is an error wrapping multiple validation
// errors returned by AllWorkerGroupReply.ValidateAll() if the designated
// constraints aren't met.
type AllWorkerGroupReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AllWorkerGroupReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AllWorkerGroupReplyMultiError) AllErrors() []error { return m }

// AllWorkerGroupReplyValidationError is the validation error returned by
// AllWorkerGroupReply.Validate if the designated constraints aren't met.
type AllWorkerGroupReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AllWorkerGroupReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AllWorkerGroupReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AllWorkerGroupReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AllWorkerGroupReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AllWorkerGroupReplyValidationError) ErrorName() string {
	return "AllWorkerGroupReplyValidationError"
}

// Error satisfies the builtin error interface
func (e AllWorkerGroupReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAllWorkerGroupReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AllWorkerGroupReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AllWorkerGroupReplyValidationError{}

// Validate checks the field values on AddWorkerGroupRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AddWorkerGroupRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddWorkerGroupRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddWorkerGroupRequestMultiError, or nil if none found.
func (m *AddWorkerGroupRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AddWorkerGroupRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := AddWorkerGroupRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDescription()) < 1 {
		err := AddWorkerGroupRequestValidationError{
			field:  "Description",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AddWorkerGroupRequestMultiError(errors)
	}

	return nil
}

// AddWorkerGroupRequestMultiError is an error wrapping multiple validation
// errors returned by AddWorkerGroupRequest.ValidateAll() if the designated
// constraints aren't met.
type AddWorkerGroupRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddWorkerGroupRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddWorkerGroupRequestMultiError) AllErrors() []error { return m }

// AddWorkerGroupRequestValidationError is the validation error returned by
// AddWorkerGroupRequest.Validate if the designated constraints aren't met.
type AddWorkerGroupRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddWorkerGroupRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddWorkerGroupRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddWorkerGroupRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddWorkerGroupRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddWorkerGroupRequestValidationError) ErrorName() string {
	return "AddWorkerGroupRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AddWorkerGroupRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddWorkerGroupRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddWorkerGroupRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddWorkerGroupRequestValidationError{}

// Validate checks the field values on AddWorkerGroupReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AddWorkerGroupReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddWorkerGroupReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddWorkerGroupReplyMultiError, or nil if none found.
func (m *AddWorkerGroupReply) ValidateAll() error {
	return m.validate(true)
}

func (m *AddWorkerGroupReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return AddWorkerGroupReplyMultiError(errors)
	}

	return nil
}

// AddWorkerGroupReplyMultiError is an error wrapping multiple validation
// errors returned by AddWorkerGroupReply.ValidateAll() if the designated
// constraints aren't met.
type AddWorkerGroupReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddWorkerGroupReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddWorkerGroupReplyMultiError) AllErrors() []error { return m }

// AddWorkerGroupReplyValidationError is the validation error returned by
// AddWorkerGroupReply.Validate if the designated constraints aren't met.
type AddWorkerGroupReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddWorkerGroupReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddWorkerGroupReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddWorkerGroupReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddWorkerGroupReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddWorkerGroupReplyValidationError) ErrorName() string {
	return "AddWorkerGroupReplyValidationError"
}

// Error satisfies the builtin error interface
func (e AddWorkerGroupReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddWorkerGroupReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddWorkerGroupReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddWorkerGroupReplyValidationError{}

// Validate checks the field values on UpdateWorkerGroupRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateWorkerGroupRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateWorkerGroupRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateWorkerGroupRequestMultiError, or nil if none found.
func (m *UpdateWorkerGroupRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateWorkerGroupRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := UpdateWorkerGroupRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := UpdateWorkerGroupRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDescription()) < 1 {
		err := UpdateWorkerGroupRequestValidationError{
			field:  "Description",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UpdateWorkerGroupRequestMultiError(errors)
	}

	return nil
}

// UpdateWorkerGroupRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateWorkerGroupRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateWorkerGroupRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateWorkerGroupRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateWorkerGroupRequestMultiError) AllErrors() []error { return m }

// UpdateWorkerGroupRequestValidationError is the validation error returned by
// UpdateWorkerGroupRequest.Validate if the designated constraints aren't met.
type UpdateWorkerGroupRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateWorkerGroupRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateWorkerGroupRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateWorkerGroupRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateWorkerGroupRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateWorkerGroupRequestValidationError) ErrorName() string {
	return "UpdateWorkerGroupRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateWorkerGroupRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateWorkerGroupRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateWorkerGroupRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateWorkerGroupRequestValidationError{}

// Validate checks the field values on DeleteWorkerGroupRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteWorkerGroupRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteWorkerGroupRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteWorkerGroupRequestMultiError, or nil if none found.
func (m *DeleteWorkerGroupRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteWorkerGroupRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := DeleteWorkerGroupRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteWorkerGroupRequestMultiError(errors)
	}

	return nil
}

// DeleteWorkerGroupRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteWorkerGroupRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteWorkerGroupRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteWorkerGroupRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteWorkerGroupRequestMultiError) AllErrors() []error { return m }

// DeleteWorkerGroupRequestValidationError is the validation error returned by
// DeleteWorkerGroupRequest.Validate if the designated constraints aren't met.
type DeleteWorkerGroupRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteWorkerGroupRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteWorkerGroupRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteWorkerGroupRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteWorkerGroupRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteWorkerGroupRequestValidationError) ErrorName() string {
	return "DeleteWorkerGroupRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteWorkerGroupRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteWorkerGroupRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteWorkerGroupRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteWorkerGroupRequestValidationError{}

// Validate checks the field values on Worker with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Worker) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Worker with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in WorkerMultiError, or nil if none found.
func (m *Worker) ValidateAll() error {
	return m.validate(true)
}

func (m *Worker) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Ip

	// no validation rules for Status

	// no validation rules for Description

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if m.GroupId != nil {
		// no validation rules for GroupId
	}

	if m.Group != nil {

		if all {
			switch v := interface{}(m.GetGroup()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WorkerValidationError{
						field:  "Group",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WorkerValidationError{
						field:  "Group",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetGroup()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WorkerValidationError{
					field:  "Group",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return WorkerMultiError(errors)
	}

	return nil
}

// WorkerMultiError is an error wrapping multiple validation errors returned by
// Worker.ValidateAll() if the designated constraints aren't met.
type WorkerMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WorkerMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WorkerMultiError) AllErrors() []error { return m }

// WorkerValidationError is the validation error returned by Worker.Validate if
// the designated constraints aren't met.
type WorkerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WorkerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WorkerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WorkerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WorkerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WorkerValidationError) ErrorName() string { return "WorkerValidationError" }

// Error satisfies the builtin error interface
func (e WorkerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWorker.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WorkerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WorkerValidationError{}

// Validate checks the field values on PageWorkerRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PageWorkerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PageWorkerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PageWorkerRequestMultiError, or nil if none found.
func (m *PageWorkerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PageWorkerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetPage() <= 0 {
		err := PageWorkerRequestValidationError{
			field:  "Page",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetPageSize() > 100 {
		err := PageWorkerRequestValidationError{
			field:  "PageSize",
			reason: "value must be less than or equal to 100",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GroupId != nil {
		// no validation rules for GroupId
	}

	if m.Name != nil {
		// no validation rules for Name
	}

	if len(errors) > 0 {
		return PageWorkerRequestMultiError(errors)
	}

	return nil
}

// PageWorkerRequestMultiError is an error wrapping multiple validation errors
// returned by PageWorkerRequest.ValidateAll() if the designated constraints
// aren't met.
type PageWorkerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PageWorkerRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PageWorkerRequestMultiError) AllErrors() []error { return m }

// PageWorkerRequestValidationError is the validation error returned by
// PageWorkerRequest.Validate if the designated constraints aren't met.
type PageWorkerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageWorkerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageWorkerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageWorkerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageWorkerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageWorkerRequestValidationError) ErrorName() string {
	return "PageWorkerRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PageWorkerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageWorkerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageWorkerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageWorkerRequestValidationError{}

// Validate checks the field values on PageWorkerReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PageWorkerReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PageWorkerReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PageWorkerReplyMultiError, or nil if none found.
func (m *PageWorkerReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PageWorkerReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PageWorkerReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PageWorkerReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PageWorkerReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return PageWorkerReplyMultiError(errors)
	}

	return nil
}

// PageWorkerReplyMultiError is an error wrapping multiple validation errors
// returned by PageWorkerReply.ValidateAll() if the designated constraints
// aren't met.
type PageWorkerReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PageWorkerReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PageWorkerReplyMultiError) AllErrors() []error { return m }

// PageWorkerReplyValidationError is the validation error returned by
// PageWorkerReply.Validate if the designated constraints aren't met.
type PageWorkerReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageWorkerReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageWorkerReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageWorkerReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageWorkerReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageWorkerReplyValidationError) ErrorName() string { return "PageWorkerReplyValidationError" }

// Error satisfies the builtin error interface
func (e PageWorkerReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageWorkerReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageWorkerReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageWorkerReplyValidationError{}

// Validate checks the field values on AddWorkerRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AddWorkerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddWorkerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddWorkerRequestMultiError, or nil if none found.
func (m *AddWorkerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AddWorkerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := AddWorkerRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetIp()) < 1 {
		err := AddWorkerRequestValidationError{
			field:  "Ip",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDescription()) < 1 {
		err := AddWorkerRequestValidationError{
			field:  "Description",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GroupId != nil {

		if m.GetGroupId() <= 0 {
			err := AddWorkerRequestValidationError{
				field:  "GroupId",
				reason: "value must be greater than 0",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return AddWorkerRequestMultiError(errors)
	}

	return nil
}

// AddWorkerRequestMultiError is an error wrapping multiple validation errors
// returned by AddWorkerRequest.ValidateAll() if the designated constraints
// aren't met.
type AddWorkerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddWorkerRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddWorkerRequestMultiError) AllErrors() []error { return m }

// AddWorkerRequestValidationError is the validation error returned by
// AddWorkerRequest.Validate if the designated constraints aren't met.
type AddWorkerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddWorkerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddWorkerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddWorkerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddWorkerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddWorkerRequestValidationError) ErrorName() string { return "AddWorkerRequestValidationError" }

// Error satisfies the builtin error interface
func (e AddWorkerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddWorkerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddWorkerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddWorkerRequestValidationError{}

// Validate checks the field values on AddWorkerReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddWorkerReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddWorkerReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddWorkerReplyMultiError,
// or nil if none found.
func (m *AddWorkerReply) ValidateAll() error {
	return m.validate(true)
}

func (m *AddWorkerReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return AddWorkerReplyMultiError(errors)
	}

	return nil
}

// AddWorkerReplyMultiError is an error wrapping multiple validation errors
// returned by AddWorkerReply.ValidateAll() if the designated constraints
// aren't met.
type AddWorkerReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddWorkerReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddWorkerReplyMultiError) AllErrors() []error { return m }

// AddWorkerReplyValidationError is the validation error returned by
// AddWorkerReply.Validate if the designated constraints aren't met.
type AddWorkerReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddWorkerReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddWorkerReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddWorkerReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddWorkerReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddWorkerReplyValidationError) ErrorName() string { return "AddWorkerReplyValidationError" }

// Error satisfies the builtin error interface
func (e AddWorkerReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddWorkerReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddWorkerReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddWorkerReplyValidationError{}

// Validate checks the field values on UpdateWorkerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateWorkerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateWorkerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateWorkerRequestMultiError, or nil if none found.
func (m *UpdateWorkerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateWorkerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := UpdateWorkerRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := UpdateWorkerRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetIp()) < 1 {
		err := UpdateWorkerRequestValidationError{
			field:  "Ip",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDescription()) < 1 {
		err := UpdateWorkerRequestValidationError{
			field:  "Description",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GroupId != nil {

		if m.GetGroupId() <= 0 {
			err := UpdateWorkerRequestValidationError{
				field:  "GroupId",
				reason: "value must be greater than 0",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return UpdateWorkerRequestMultiError(errors)
	}

	return nil
}

// UpdateWorkerRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateWorkerRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateWorkerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateWorkerRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateWorkerRequestMultiError) AllErrors() []error { return m }

// UpdateWorkerRequestValidationError is the validation error returned by
// UpdateWorkerRequest.Validate if the designated constraints aren't met.
type UpdateWorkerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateWorkerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateWorkerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateWorkerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateWorkerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateWorkerRequestValidationError) ErrorName() string {
	return "UpdateWorkerRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateWorkerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateWorkerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateWorkerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateWorkerRequestValidationError{}

// Validate checks the field values on EnableWorkerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *EnableWorkerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EnableWorkerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EnableWorkerRequestMultiError, or nil if none found.
func (m *EnableWorkerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *EnableWorkerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := EnableWorkerRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return EnableWorkerRequestMultiError(errors)
	}

	return nil
}

// EnableWorkerRequestMultiError is an error wrapping multiple validation
// errors returned by EnableWorkerRequest.ValidateAll() if the designated
// constraints aren't met.
type EnableWorkerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EnableWorkerRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EnableWorkerRequestMultiError) AllErrors() []error { return m }

// EnableWorkerRequestValidationError is the validation error returned by
// EnableWorkerRequest.Validate if the designated constraints aren't met.
type EnableWorkerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EnableWorkerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EnableWorkerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EnableWorkerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EnableWorkerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EnableWorkerRequestValidationError) ErrorName() string {
	return "EnableWorkerRequestValidationError"
}

// Error satisfies the builtin error interface
func (e EnableWorkerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEnableWorkerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EnableWorkerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EnableWorkerRequestValidationError{}

// Validate checks the field values on DisableWorkerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DisableWorkerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DisableWorkerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DisableWorkerRequestMultiError, or nil if none found.
func (m *DisableWorkerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DisableWorkerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := DisableWorkerRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DisableWorkerRequestMultiError(errors)
	}

	return nil
}

// DisableWorkerRequestMultiError is an error wrapping multiple validation
// errors returned by DisableWorkerRequest.ValidateAll() if the designated
// constraints aren't met.
type DisableWorkerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DisableWorkerRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DisableWorkerRequestMultiError) AllErrors() []error { return m }

// DisableWorkerRequestValidationError is the validation error returned by
// DisableWorkerRequest.Validate if the designated constraints aren't met.
type DisableWorkerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DisableWorkerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DisableWorkerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DisableWorkerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DisableWorkerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DisableWorkerRequestValidationError) ErrorName() string {
	return "DisableWorkerRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DisableWorkerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDisableWorkerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DisableWorkerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DisableWorkerRequestValidationError{}

// Validate checks the field values on DeleteWorkerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteWorkerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteWorkerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteWorkerRequestMultiError, or nil if none found.
func (m *DeleteWorkerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteWorkerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := DeleteWorkerRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteWorkerRequestMultiError(errors)
	}

	return nil
}

// DeleteWorkerRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteWorkerRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteWorkerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteWorkerRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteWorkerRequestMultiError) AllErrors() []error { return m }

// DeleteWorkerRequestValidationError is the validation error returned by
// DeleteWorkerRequest.Validate if the designated constraints aren't met.
type DeleteWorkerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteWorkerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteWorkerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteWorkerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteWorkerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteWorkerRequestValidationError) ErrorName() string {
	return "DeleteWorkerRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteWorkerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteWorkerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteWorkerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteWorkerRequestValidationError{}
