
env: TEST
server:
  http:
    host: 127.0.0.1
    port: 7005
    timeout: 10s
    marshal:
      emitUnpopulated: true
      useProtoNames: true
  grpc:
    host: 127.0.0.1
    port: 8005
    timeout: 10s
log:
  level: 0
  output:
    - stdout
    - file
  file:
    name: ./tmp/runtime/output.log
    maxSize: 1
    maxBackup: 5
    maxAge: 1
    compress: false
redis:
  cache:
    enable: true
    host: 127.0.0.1:6379
    username:
    password:
database:
  system:
    enable: true #是否启用数据库
    drive: mysql #数据库类型
    autoCreate: true #是否自动创建数据库
    connect:
      username: root
      password: root
      host: 127.0.0.1
      port: 3306
      dbName: cron
      option: ?charset=utf8mb4&parseTime=True&loc=Local
    config:
      transformError:
        enable: true
      initializer:
        enable: false
        path: deploy/data.sql
      maxLifetime: 2h #最大生存时间
      maxOpenConn: 20 #最大连接数量
      maxIdleConn: 10 #最大空闲数量
      logLevel: 3 #日志等级
      slowThreshold: 2s #慢sql阈值
pool: #并非池配置
  size: 10000 #最大协程数量
  expiryDuration: 30s #过期时间
  preAlloc: true #是否预分配
  maxBlockingTasks: 1000 #最大的并发任务
  nonblocking: true #设置为true时maxBlockingTasks将失效，不限制并发任务
business:
  key: value